---
title: "crop-yields"
author: "Alex Cookson"
date: "01/09/2020"
output: html_document
---

```{r setup, warning = FALSE, message = FALSE}
library(tidyverse)

theme_set(theme_minimal())

key_crop_yields <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-01/key_crop_yields.csv')
fertilizer <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-01/cereal_crop_yield_vs_fertilizer_application.csv')
tractors <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-01/cereal_yields_vs_tractor_inputs_in_agriculture.csv')
land_use <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-01/land_use_vs_yield_change_in_cereal_production.csv')
arable_land <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-01/arable_land_pin.csv')
```

```{r north-america-tractors}
tractors_clean <- tractors %>%
  rename(country = 1,
         code = 2,
         year = 3,
         tractors_per_100_km2 = 4,
         cereal_kg_per_hectare = 5,
         population = 6)

tractors_clean %>%
  filter(country %in% c("Canada", "United States", "Mexico"),
         !is.na(tractors_per_100_km2)) %>%
  mutate(year = as.integer(year)) %>%
  ggplot(aes(year, tractors_per_100_km2, colour = country)) +
  geom_point() +
  geom_line() +
  theme(axis.text.x = element_text(hjust = 1, angle = 45))
```

