---
title: "palmer-penguins"
author: "Alex Cookson"
date: "27/07/2020"
output: html_document
---

```{r setup}
library(tidyverse)
library(mapproj)

penguins <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-28/penguins.csv')

penguins_raw <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-28/penguins_raw.csv')
```

```{r}
sites <- read_csv("./2020/2020-07-28 (Palmer Penguins)/ref/all_MAPPPD_sites.csv") %>%
  janitor::clean_names() %>%
  rename(lon = longitude_epsg_4326,
         lat = latitude_epsg_4326)
```

```{r antarctica-map}
library(ggplot2) # For graphing
library(mapproj) # For the polar orthographic map projection


# Get geospatial data for Antarctica only
antarctica <- map_data("world", region = "Antarctica")

ggplot() +
  geom_polygon(data = antarctica,
               aes(long, lat, group = group),
               fill = "#506B8E") +
  geom_point(data = sites, aes(lon, lat),
             colour = "#C33C54",
             size = 0.8) +
  # This is where the magic happens
  coord_map("ortho", orientation = c(-90, 0, 0)) +
  theme_map()
```


```{r antarctica-map}
library(ggplot2) # For graphing
library(mapproj) # For the polar orthographic map projection
library(ggthemes) # For theme_map()

# Get geospatial data for Antarctica only
antarctica <- map_data("world", region = "Antarctica")

ggplot(antarctica, aes(long, lat, group = group)) +
  geom_polygon(fill = "#506B8E") +
  # This is where the magic happens
  coord_map("ortho", orientation = c(-90, 0, 0)) +
  theme_map()
```


